import React,{Component,useEffect,useState} from 'react';
import AdminApp from './AdminApp';
import { adminAuthRequest,installAdminSessionFetch,setAdminUnauthorizedHandler } from './authFetch';

class AdminErrorBoundary extends Component{constructor(p){super(p);this.state={error:null}}static getDerivedStateFromError(error){return{error}}componentDidCatch(error,info){console.error('Admin workspace error',error,info)}render(){if(!this.state.error)return this.props.children;return <main className="admin-fatal"><div><p className="eyebrow">Leaf Fairy Admin</p><h1>Workspace needs a refresh</h1><p>An unexpected interface error interrupted the merchant workspace. Your server data has not been deleted.</p><button onClick={()=>window.location.reload()}>Reload workspace</button></div></main>}}

export default function AdminRuntime(){
 const [online,setOnline]=useState(()=>navigator.onLine),[pending,setPending]=useState(0),[confirmAction,setConfirmAction]=useState(null),[auth,setAuth]=useState({checking:true,user:null}),[identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[authError,setAuthError]=useState(''),[signingIn,setSigningIn]=useState(false);
 useEffect(()=>{const restore=installAdminSessionFetch();setAdminUnauthorizedHandler(()=>setAuth({checking:false,user:null}));adminAuthRequest('/session').then(({user})=>setAuth({checking:false,user})).catch(()=>setAuth({checking:false,user:null}));return()=>{setAdminUnauthorizedHandler(null);restore()}},[]);
 useEffect(()=>{const up=()=>setOnline(true),down=()=>setOnline(false);window.addEventListener('online',up);window.addEventListener('offline',down);const original=window.fetch.bind(window);window.fetch=(...args)=>{setPending(n=>n+1);return original(...args).finally(()=>setPending(n=>Math.max(0,n-1)))};return()=>{window.removeEventListener('online',up);window.removeEventListener('offline',down);window.fetch=original}},[auth.user]);
 useEffect(()=>{const protect=event=>{const button=event.target.closest?.('button');if(!button||button.dataset.confirmed==='true'||button.disabled)return;const label=button.textContent.trim().toLowerCase(),orderStatus=button.closest('.admin-detail')?.querySelector('.order-status select')?.value,archive=label==='archive'||label.startsWith('archive '),cancelOrder=label.includes('save order status')&&orderStatus==='cancelled';if(!archive&&!cancelOrder)return;event.preventDefault();event.stopPropagation();setConfirmAction({button,title:cancelOrder?'Cancel this order?':'Archive this item?',body:cancelOrder?'This changes the order status to cancelled. Confirm only after checking the customer and payment details.':'Archived content stays in the system but is removed from active merchant choices.',confirmLabel:cancelOrder?'Cancel order':'Archive'})};document.addEventListener('click',protect,true);return()=>document.removeEventListener('click',protect,true)},[]);
 const proceed=()=>{const button=confirmAction?.button;if(!button)return setConfirmAction(null);button.dataset.confirmed='true';setConfirmAction(null);button.click();queueMicrotask(()=>delete button.dataset.confirmed)};
 async function signIn(e){e.preventDefault();setSigningIn(true);setAuthError('');try{const {user}=await adminAuthRequest('/login',{method:'POST',body:JSON.stringify({identifier,password})});setPassword('');setAuth({checking:false,user})}catch(error){setAuthError(error.status===429?'Too many login attempts. Please wait and try again.':error.message)}finally{setSigningIn(false)}}
 async function signOut(){try{await adminAuthRequest('/logout',{method:'POST'})}catch{}finally{setPassword('');setAuth({checking:false,user:null})}}
 if(auth.checking)return <main className="admin-login admin-auth-check"><div><p className="eyebrow">Leaf Fairy Atelier</p><h1>Securing Admin Studio</h1><p>Checking your authenticated session…</p></div></main>;
 if(!auth.user)return <main className="admin-login"><form onSubmit={signIn}><p className="eyebrow">Leaf Fairy Atelier</p><h1>Admin Studio</h1><p>Sign in to the private merchant workspace.</p><label>Username or email<input autoComplete="username" required value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="admin"/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{authError&&<p className="admin-error" role="alert">{authError}</p>}<button disabled={signingIn}>{signingIn?'Signing in…':'Sign in'}</button><small className="admin-login-note">Testing only: run the admin seed to create the development account. Never use the testing password in production.</small></form></main>;
 return <AdminErrorBoundary>{!online&&<div className="admin-network" role="status">You are offline. Changes cannot be saved until the connection returns.</div>}{pending>0&&<div className="admin-progress" role="status" aria-label="Admin request in progress"><span/></div>}<div className={pending>0?'admin-runtime-busy':''} aria-busy={pending>0}><AdminApp authenticatedUser={auth.user} onAuthenticatedLogout={signOut}/></div>{confirmAction&&<div className="admin-confirm-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setConfirmAction(null)}}><section className="admin-confirm" role="alertdialog" aria-modal="true" aria-labelledby="admin-confirm-title"><p className="eyebrow">Confirm action</p><h2 id="admin-confirm-title">{confirmAction.title}</h2><p>{confirmAction.body}</p><div><button className="secondary-action" onClick={()=>setConfirmAction(null)}>Keep editing</button><button className="primary-action danger-action" onClick={proceed}>{confirmAction.confirmLabel}</button></div></section></div>}</AdminErrorBoundary>
}
