import { useEffect, useState } from 'react';
import { Boxes, ClipboardList, FilePenLine, LayoutDashboard, MessageSquareText, PackageSearch, Save, ShieldCheck } from 'lucide-react';

const API_BASE = import.meta.env.VITE_API_URL || '/api';
async function adminRequest(path,key,options={}) { const response=await fetch(`${API_BASE}/admin${path}`,{...options,headers:{'Content-Type':'application/json','x-admin-key':key,...options.headers}}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.message||'Admin request failed'); return data; }
const emptyContent={key:'',section:'homepage',eyebrow:'',title:'',body:'',image:'',ctaLabel:'',ctaHref:'',enabled:true,sortOrder:0};

export default function AdminApp(){
  const [key,setKey]=useState(()=>sessionStorage.getItem('leaf-fairy-admin-key')||''); const [connected,setConnected]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [tab,setTab]=useState('dashboard'); const [dashboard,setDashboard]=useState(null); const [products,setProducts]=useState([]); const [inventory,setInventory]=useState([]); const [orders,setOrders]=useState([]); const [enquiries,setEnquiries]=useState([]); const [content,setContent]=useState([]); const [draft,setDraft]=useState(emptyContent);
  async function connect(event){event?.preventDefault();setError('');try{const stats=await adminRequest('/dashboard',key);sessionStorage.setItem('leaf-fairy-admin-key',key);setDashboard(stats);setConnected(true)}catch(err){setError(err.message)}}
  useEffect(()=>{if(!connected)return;setError(''); const loaders={dashboard:()=>adminRequest('/dashboard',key).then(setDashboard),products:()=>adminRequest('/products',key).then(setProducts),inventory:()=>adminRequest('/inventory',key).then(setInventory),orders:()=>adminRequest('/orders',key).then(setOrders),enquiries:()=>adminRequest('/enquiries',key).then(setEnquiries),content:()=>adminRequest('/content',key).then(setContent)}; loaders[tab]?.().catch((err)=>setError(err.message));},[tab,connected,key]);
  async function saveInventory(item){try{const updated=await adminRequest(`/inventory/${item._id}`,key,{method:'PATCH',body:JSON.stringify({price:Number(item.price),stock:Number(item.stock),active:item.active})});setInventory((items)=>items.map((entry)=>entry._id===updated._id?updated:entry));setNotice(`Saved ${item.sku}`)}catch(err){setError(err.message)}}
  async function saveProduct(product){try{const updated=await adminRequest(`/products/${product._id}`,key,{method:'PATCH',body:JSON.stringify({name:product.name,description:product.description,priceRange:product.priceRange,featured:Boolean(product.featured)})});setProducts((items)=>items.map((entry)=>entry._id===updated._id?updated:entry));setNotice(`Saved ${updated.name}`)}catch(err){setError(err.message)}}
  async function saveContent(event){event.preventDefault();if(!draft.key.trim())return setError('Content key is required');try{const saved=await adminRequest(`/content/${encodeURIComponent(draft.key.trim())}`,key,{method:'PUT',body:JSON.stringify({...draft,key:undefined,sortOrder:Number(draft.sortOrder)})});setContent((items)=>{const exists=items.some((x)=>x.key===saved.key);return exists?items.map((x)=>x.key===saved.key?saved:x):[...items,saved]});setDraft(saved);setNotice(`Saved content: ${saved.key}`)}catch(err){setError(err.message)}}
  if(!connected)return <main className="admin-login"><form onSubmit={connect}><ShieldCheck size={28}/><p className="eyebrow">Leaf Fairy Atelier</p><h1>Admin Studio</h1><p>Private merchant workspace for catalogue, inventory, orders and content operations.</p><label>Admin access key<input type="password" required value={key} onChange={(e)=>setKey(e.target.value)} /></label>{error&&<p className="admin-error">{error}</p>}<button type="submit">Enter studio</button></form></main>;
  const tabs=[['dashboard','Overview',LayoutDashboard],['products','Products',PackageSearch],['inventory','Inventory',Boxes],['content','Content',FilePenLine],['orders','Orders',ClipboardList],['enquiries','Enquiries',MessageSquareText]];
  return <div className="admin-shell"><aside className="admin-sidebar"><div><p className="eyebrow">Leaf Fairy</p><h2>Admin Studio</h2></div><nav>{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setNotice('')}}><Icon size={16}/>{label}</button>)}</nav><button className="admin-signout" onClick={()=>{sessionStorage.removeItem('leaf-fairy-admin-key');setConnected(false);setKey('')}}>Lock studio</button></aside><main className="admin-main"><header><p className="eyebrow">Merchant workspace</p><h1>{tabs.find(([id])=>id===tab)?.[1]}</h1></header>{error&&<p className="admin-error">{error}</p>}{notice&&<p className="admin-notice">{notice}</p>}
  {tab==='dashboard'&&dashboard&&<section className="admin-stats">{Object.entries(dashboard).map(([label,value])=><article key={label}><span>{label.replace(/([A-Z])/g,' $1')}</span><strong>{value}</strong></article>)}</section>}
  {tab==='products'&&<section className="admin-table"><div className="admin-row admin-row-head admin-product-row"><span>Product</span><span>Description</span><span>Display price</span><span>Featured</span><span></span></div>{products.map((p)=><div className="admin-row admin-product-row" key={p._id}><input aria-label="Product name" value={p.name||''} onChange={(e)=>setProducts((all)=>all.map((x)=>x._id===p._id?{...x,name:e.target.value}:x))}/><textarea aria-label="Product description" value={p.description||''} onChange={(e)=>setProducts((all)=>all.map((x)=>x._id===p._id?{...x,description:e.target.value}:x))}/><input aria-label="Display price" value={p.priceRange||''} onChange={(e)=>setProducts((all)=>all.map((x)=>x._id===p._id?{...x,priceRange:e.target.value}:x))}/><label className="admin-toggle"><input type="checkbox" checked={Boolean(p.featured)} onChange={(e)=>setProducts((all)=>all.map((x)=>x._id===p._id?{...x,featured:e.target.checked}:x))}/>Featured</label><button className="admin-save" onClick={()=>saveProduct(p)} aria-label={`Save ${p.name}`}><Save size={15}/></button></div>)}</section>}
  {tab==='inventory'&&<section className="admin-table"><div className="admin-row admin-row-head admin-inventory-row"><span>Product / SKU</span><span>Price ₹</span><span>Stock</span><span>Status</span><span></span></div>{inventory.map((item)=><div className="admin-row admin-inventory-row" key={item._id}><span><b>{item.product?.name||'Product'}</b><small>{item.sku}</small></span><input type="number" min="0" value={item.price} onChange={(e)=>setInventory((all)=>all.map((x)=>x._id===item._id?{...x,price:e.target.value}:x))}/><input type="number" min="0" value={item.stock} onChange={(e)=>setInventory((all)=>all.map((x)=>x._id===item._id?{...x,stock:e.target.value}:x))}/><label className="admin-toggle"><input type="checkbox" checked={item.active} onChange={(e)=>setInventory((all)=>all.map((x)=>x._id===item._id?{...x,active:e.target.checked}:x))}/>{item.active?'Active':'Hidden'}</label><button className="admin-save" onClick={()=>saveInventory(item)} aria-label={`Save ${item.sku}`}><Save size={15}/></button></div>)}</section>}
  {tab==='content'&&<section className="admin-content-layout"><aside className="admin-content-list"><button onClick={()=>setDraft(emptyContent)}>+ New content block</button>{content.map((block)=><button key={block.key} className={draft.key===block.key?'active':''} onClick={()=>setDraft(block)}><b>{block.title||block.key}</b><small>{block.section} · {block.key}</small></button>)}</aside><form className="admin-editor" onSubmit={saveContent}><div className="admin-form-grid"><label>Key<input required disabled={Boolean(draft._id)} value={draft.key||''} onChange={(e)=>setDraft({...draft,key:e.target.value})}/></label><label>Section<input required value={draft.section||''} onChange={(e)=>setDraft({...draft,section:e.target.value})}/></label><label>Eyebrow<input value={draft.eyebrow||''} onChange={(e)=>setDraft({...draft,eyebrow:e.target.value})}/></label><label>Title<input value={draft.title||''} onChange={(e)=>setDraft({...draft,title:e.target.value})}/></label><label className="wide">Body<textarea rows="6" value={draft.body||''} onChange={(e)=>setDraft({...draft,body:e.target.value})}/></label><label className="wide">Image URL / path<input value={draft.image||''} onChange={(e)=>setDraft({...draft,image:e.target.value})}/></label><label>CTA label<input value={draft.ctaLabel||''} onChange={(e)=>setDraft({...draft,ctaLabel:e.target.value})}/></label><label>CTA link<input value={draft.ctaHref||''} onChange={(e)=>setDraft({...draft,ctaHref:e.target.value})}/></label><label>Sort order<input type="number" value={draft.sortOrder??0} onChange={(e)=>setDraft({...draft,sortOrder:e.target.value})}/></label><label className="admin-toggle editor-toggle"><input type="checkbox" checked={draft.enabled!==false} onChange={(e)=>setDraft({...draft,enabled:e.target.checked})}/>Published</label></div><button className="primary-action" type="submit"><Save size={15}/> Save content block</button></form></section>}
  {tab==='orders'&&<section className="admin-table">{orders.length?orders.map((order)=><div className="admin-row" key={order._id}><span><b>{order.orderNumber}</b><small>{order.deliveryAddress?.email||'—'}</small></span><span>{order.status}</span><span>₹{order.subtotal}</span></div>):<p className="admin-empty">No orders yet.</p>}</section>}
  {tab==='enquiries'&&<section className="admin-table">{enquiries.length?enquiries.map((item)=><div className="admin-row" key={item._id}><span><b>{item.name}</b><small>{item.email}</small></span><span>{item.type||'Enquiry'}</span><span>{item.message}</span></div>):<p className="admin-empty">No enquiries yet.</p>}</section>}</main></div>;
}
