import { useEffect, useState } from 'react';
import { Boxes, ClipboardList, LayoutDashboard, MessageSquareText, PackageSearch, Save, ShieldCheck } from 'lucide-react';

const API_BASE = import.meta.env.VITE_API_URL || '/api';
async function adminRequest(path,key,options={}) { const response=await fetch(`${API_BASE}/admin${path}`,{...options,headers:{'Content-Type':'application/json','x-admin-key':key,...options.headers}}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.message||'Admin request failed'); return data; }

export default function AdminPage(){
  const [key,setKey]=useState(()=>sessionStorage.getItem('leaf-fairy-admin-key')||''); const [connected,setConnected]=useState(false); const [error,setError]=useState(''); const [tab,setTab]=useState('dashboard'); const [dashboard,setDashboard]=useState(null); const [products,setProducts]=useState([]); const [inventory,setInventory]=useState([]); const [orders,setOrders]=useState([]); const [enquiries,setEnquiries]=useState([]);
  async function connect(event){event?.preventDefault();setError('');try{const stats=await adminRequest('/dashboard',key);sessionStorage.setItem('leaf-fairy-admin-key',key);setDashboard(stats);setConnected(true)}catch(err){setError(err.message)}}
  useEffect(()=>{if(!connected)return; const loaders={products:()=>adminRequest('/products',key).then(setProducts),inventory:()=>adminRequest('/inventory',key).then(setInventory),orders:()=>adminRequest('/orders',key).then(setOrders),enquiries:()=>adminRequest('/enquiries',key).then(setEnquiries)}; loaders[tab]?.().catch((err)=>setError(err.message));},[tab,connected,key]);
  async function saveInventory(item){try{const updated=await adminRequest(`/inventory/${item._id}`,key,{method:'PATCH',body:JSON.stringify({price:Number(item.price),stock:Number(item.stock),active:item.active})});setInventory((items)=>items.map((entry)=>entry._id===updated._id?updated:entry));}catch(err){setError(err.message)}}
  if(!connected)return <main className="admin-login"><form onSubmit={connect}><ShieldCheck size={28}/><p className="eyebrow">Leaf Fairy Atelier</p><h1>Admin Studio</h1><p>Private merchant workspace for catalogue, inventory, orders and content operations.</p><label>Admin access key<input type="password" required value={key} onChange={(e)=>setKey(e.target.value)} /></label>{error&&<p className="admin-error">{error}</p>}<button type="submit">Enter studio</button></form></main>;
  const tabs=[['dashboard','Overview',LayoutDashboard],['products','Products',PackageSearch],['inventory','Inventory',Boxes],['orders','Orders',ClipboardList],['enquiries','Enquiries',MessageSquareText]];
  return <div className="admin-shell"><aside className="admin-sidebar"><div><p className="eyebrow">Leaf Fairy</p><h2>Admin Studio</h2></div><nav>{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</nav><button className="admin-signout" onClick={()=>{sessionStorage.removeItem('leaf-fairy-admin-key');setConnected(false);setKey('')}}>Lock studio</button></aside><main className="admin-main"><header><p className="eyebrow">Merchant workspace</p><h1>{tabs.find(([id])=>id===tab)?.[1]}</h1></header>{error&&<p className="admin-error">{error}</p>}{tab==='dashboard'&&dashboard&&<section className="admin-stats">{Object.entries(dashboard).map(([label,value])=><article key={label}><span>{label.replace(/([A-Z])/g,' $1')}</span><strong>{value}</strong></article>)}</section>}{tab==='products'&&<section className="admin-table"><div className="admin-row admin-row-head"><span>Product</span><span>Collection</span><span>Display price</span></div>{products.map((p)=><div className="admin-row" key={p._id}><span><b>{p.name}</b><small>{p.description}</small></span><span>{p.collectionSlug}</span><span>{p.priceRange||'—'}</span></div>)}</section>}{tab==='inventory'&&<section className="admin-table"><div className="admin-row admin-row-head admin-inventory-row"><span>Product / SKU</span><span>Price ₹</span><span>Stock</span><span>Status</span><span></span></div>{inventory.map((item)=><div className="admin-row admin-inventory-row" key={item._id}><span><b>{item.product?.name||'Product'}</b><small>{item.sku}</small></span><input type="number" min="0" value={item.price} onChange={(e)=>setInventory((all)=>all.map((x)=>x._id===item._id?{...x,price:e.target.value}:x))}/><input type="number" min="0" value={item.stock} onChange={(e)=>setInventory((all)=>all.map((x)=>x._id===item._id?{...x,stock:e.target.value}:x))}/><label className="admin-toggle"><input type="checkbox" checked={item.active} onChange={(e)=>setInventory((all)=>all.map((x)=>x._id===item._id?{...x,active:e.target.checked}:x))}/>{item.active?'Active':'Hidden'}</label><button onClick={()=>saveInventory(item)} aria-label={`Save ${item.sku}`}><Save size={15}/></button></div>)}</section>}{tab==='orders'&&<section className="admin-table">{orders.length?orders.map((order)=><div className="admin-row" key={order._id}><span><b>{order.orderNumber}</b><small>{order.customer?.email}</small></span><span>{order.status}</span><span>₹{order.total}</span></div>):<p className="admin-empty">No orders yet.</p>}</section>}{tab==='enquiries'&&<section className="admin-table">{enquiries.length?enquiries.map((item)=><div className="admin-row" key={item._id}><span><b>{item.name}</b><small>{item.email}</small></span><span>{item.type||'Enquiry'}</span><span>{item.message}</span></div>):<p className="admin-empty">No enquiries yet.</p>}</section>}</main></div>;
}
