import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import SiteHeader from '../components/SiteHeader.jsx';
import SiteFooter from '../components/SiteFooter.jsx';
import { api } from '../api/client.js';
import { useCommerce } from '../state/CommerceContext.jsx';

const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);

export default function CheckoutPage() {
  const { cart, clearCart } = useCommerce(); const [products, setProducts] = useState([]); const [quote, setQuote] = useState(null); const [quoteError, setQuoteError] = useState(''); const [submitting, setSubmitting] = useState(false); const [order, setOrder] = useState(null); const [contact, setContact] = useState({ email: '', name: '', phone: '', address: '', city: '', state: '', pincode: '' });
  const items = useMemo(() => cart.map(({ productId, quantity }) => ({ productId, quantity })), [cart]);
  useEffect(() => { api.get('/products').then((value) => setProducts(Array.isArray(value) ? value : [])).catch(() => setProducts([])); }, []);
  useEffect(() => { if (!items.length) return; api.post('/commerce/quote', { items }).then(setQuote).catch((error) => setQuoteError(error.message)); }, [items]);
  const lines = cart.map((line) => ({ ...line, product: products.find((p) => p._id === line.productId) })).filter((line) => line.product);
  async function placeOrder(event) { event.preventDefault(); setSubmitting(true); try { const created = await api.post('/commerce/orders', { items, deliveryAddress: contact }); setOrder(created); clearCart(); } catch (error) { setQuoteError(error.message); } finally { setSubmitting(false); } }
  if (order) return <div className="account-page"><SiteHeader /><main className="checkout-empty"><p className="eyebrow">Order received</p><h1>Thank you.</h1><p>Your reference is <strong>{order.orderNumber}</strong>. Payment status: {order.paymentStatus}.</p><Link className="account-primary" to="/shop">Continue shopping</Link></main><SiteFooter /></div>;
  if (!cart.length) return <div className="account-page"><SiteHeader /><main className="checkout-empty"><h1>Your bag is empty.</h1><Link className="account-primary" to="/shop">Return to shop</Link></main><SiteFooter /></div>;
  return <div className="account-page"><SiteHeader /><main className="checkout-shell"><form className="checkout-form" onSubmit={placeOrder}><p className="eyebrow">Secure checkout</p><h1>Delivery details</h1><div className="checkout-fields"><label>Email<input required type="email" value={contact.email} onChange={(e) => setContact({ ...contact, email: e.target.value })} /></label><label>Full name<input required value={contact.name} onChange={(e) => setContact({ ...contact, name: e.target.value })} /></label><label>Phone<input required value={contact.phone} onChange={(e) => setContact({ ...contact, phone: e.target.value })} /></label><label className="wide">Address<input required value={contact.address} onChange={(e) => setContact({ ...contact, address: e.target.value })} /></label><label>City<input required value={contact.city} onChange={(e) => setContact({ ...contact, city: e.target.value })} /></label><label>State<input required value={contact.state} onChange={(e) => setContact({ ...contact, state: e.target.value })} /></label><label>Pincode<input required inputMode="numeric" value={contact.pincode} onChange={(e) => setContact({ ...contact, pincode: e.target.value })} /></label></div>{quoteError && <p className="checkout-note" role="alert">{quoteError}</p>}<p className="checkout-note">Prices and stock are revalidated by the server before the order is created. Online payment is enabled only when a payment provider is configured.</p><button className="account-primary" disabled={!quote || submitting}>{submitting ? 'Creating order…' : 'Place order'}</button></form><aside className="checkout-summary"><p className="eyebrow">Your selection</p>{lines.map((line) => <div className="checkout-line" key={line.productId}><span>{line.product.name}</span><b>× {line.quantity}</b></div>)}{quote ? <><div className="checkout-line"><span>Subtotal</span><b>{money(quote.subtotal)}</b></div><p>Inventory and pricing verified by Leaf Fairy commerce API.</p></> : <p>Validating current pricing and availability…</p>}</aside></main><SiteFooter /></div>;
}
