import { Router } from 'express';
import { adminAccess } from '../middleware/adminAccess.js';
import { dashboard, products, updateProduct, collections, updateCollection, inventory, updateInventory, orders, updateOrder, enquiries, updateEnquiry, content, saveContent } from '../controllers/admin.js';

const router = Router();
router.use(adminAccess);
router.get('/dashboard', dashboard);
router.get('/products', products);
router.patch('/products/:id', updateProduct);
router.get('/collections', collections);
router.patch('/collections/:id', updateCollection);
router.get('/inventory', inventory);
router.patch('/inventory/:id', updateInventory);
router.get('/orders', orders);
router.patch('/orders/:id', updateOrder);
router.get('/enquiries', enquiries);
router.patch('/enquiries/:id', updateEnquiry);
router.get('/content', content);
router.put('/content/:key', saveContent);
export default router;
